services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3004:3004'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://code-joki.web.id
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:3004 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - code-joki-network

networks:
  code-joki-network:
    driver: bridge